import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        page: 'var(--color-page-bg)',
        canvas: 'var(--color-canvas-bg)',
        dot: 'var(--color-canvas-dot)',
        surface: {
          DEFAULT: 'var(--color-surface)',
          raised: 'var(--color-surface-raised)',
          sunken: 'var(--color-surface-sunken)',
          section: 'var(--color-surface-form-section)',
          input: 'var(--color-surface-input)',
          disabled: 'var(--color-surface-disabled)',
        },
        background: {
          base: 'var(--color-surface)',
          highlight: 'var(--color-surface-sunken)',
          muted: 'var(--color-surface-form-section)',
          emphasis: 'var(--color-text-primary)',
          disabled: 'var(--color-surface-disabled)',
        },
        text: {
          base: 'var(--color-text-primary)',
          primary: 'var(--color-text-primary)',
          body: 'var(--color-text-body)',
          muted: 'var(--color-text-muted)',
          placeholder: 'var(--color-text-placeholder)',
          disabled: 'var(--color-text-disabled)',
          inverse: 'var(--color-text-inverse)',
          brand: 'var(--color-text-brand)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          base: 'var(--color-border)',
          muted: 'var(--color-border-subtle)',
          subtle: 'var(--color-border-subtle)',
          brand: 'var(--color-border-brand)',
          input: 'var(--color-border-input)',
          disabled: 'var(--color-border-disabled)',
        },
        brand: {
          DEFAULT: 'var(--color-brand)',
          hover: 'var(--color-brand-hover)',
          active: 'var(--color-brand-active)',
          subtle: 'var(--color-brand-subtle)',
        },
        button: {
          primary: 'var(--color-btn-primary-bg)',
          'primary-fg': 'var(--color-btn-primary-fg)',
          secondary: 'var(--color-btn-secondary-bg)',
          'secondary-fg': 'var(--color-btn-secondary-fg)',
          'ghost-fg': 'var(--color-btn-ghost-fg)',
        },
        btn: {
          primaryBg: 'var(--color-btn-primary-bg)',
          primaryFg: 'var(--color-btn-primary-fg)',
          primaryHover: 'var(--color-btn-primary-hover)',
          secondaryBg: 'var(--color-btn-secondary-bg)',
          secondaryFg: 'var(--color-btn-secondary-fg)',
          secondaryBorder: 'var(--color-btn-secondary-border)',
          ghostFg: 'var(--color-btn-ghost-fg)',
          ghostHover: 'var(--color-btn-ghost-hover-bg)',
          destructiveBg: 'var(--color-btn-destructive-bg)',
          destructiveFg: 'var(--color-btn-destructive-fg)',
        },
        link: {
          base: 'var(--color-text-brand)',
          hover: 'var(--color-text-brand-hover)',
        },
        icon: {
          DEFAULT: 'var(--color-icon)',
          base: 'var(--color-icon)',
          brand: 'var(--color-icon-brand)',
          muted: 'var(--color-icon-muted)',
          inverse: 'var(--color-icon-inverse)',
          onBrand: 'var(--color-icon-on-brand)',
        },
        topbar: {
          bg: 'var(--color-topbar-bg)',
          pillBg: 'var(--color-topbar-pill-bg)',
          pillBorder: 'var(--color-topbar-pill-border)',
          avatarBg: 'var(--color-avatar-btn-bg)',
          avatarFg: 'var(--color-avatar-btn-fg)',
        },
        module: {
          headerBg: 'var(--color-module-header-bg)',
          headerFg: 'var(--color-module-header-fg)',
          addBg: 'var(--color-add-btn-bg)',
          addFg: 'var(--color-add-btn-fg)',
        },
        dock: {
          bg: 'var(--color-dock-bg)',
          border: 'var(--color-dock-border)',
          activeBg: 'var(--color-dock-item-active-bg)',
          activeBorder: 'var(--color-dock-item-active-border)',
          activeFg: 'var(--color-dock-item-active-fg)',
          itemFg: 'var(--color-dock-item-fg)',
          separator: 'var(--color-dock-separator)',
        },
        step: {
          activeBg: 'var(--color-step-active-bg)',
          activeFg: 'var(--color-step-active-fg)',
          inactiveFg: 'var(--color-step-inactive-fg)',
          inactiveBorder: 'var(--color-step-inactive-border)',
        },
        badge: {
          bg: 'var(--color-badge-bg)',
          fg: 'var(--color-badge-fg)',
        },
        preview: {
          bg: 'var(--color-preview-bg)',
          border: 'var(--color-preview-border)',
          heading: 'var(--color-preview-heading)',
          label: 'var(--color-preview-label)',
          body: 'var(--color-preview-body)',
          divider: 'var(--color-preview-divider)',
          footer: 'var(--color-preview-footer)',
        },
        feedback: {
          error: 'var(--color-error)',
          errorBase: 'var(--color-error)',
          errorBg: 'var(--color-error-bg)',
          errorText: 'var(--color-error-text)',
          success: 'var(--color-success)',
          successBase: 'var(--color-success)',
          successBg: 'var(--color-success-bg)',
          successText: 'var(--color-success-text)',
          warning: 'var(--color-warning)',
          warningBase: 'var(--color-warning)',
          warningBg: 'var(--color-warning-bg)',
          warningText: 'var(--color-warning-text)',
          info: 'var(--color-info)',
          infoBase: 'var(--color-info)',
          infoBg: 'var(--color-info-bg)',
          infoText: 'var(--color-info-text)',
        },
      },
      spacing: {
        xs: 'var(--spacing-xs)',
        sm: 'var(--spacing-sm)',
        md: 'var(--spacing-md)',
        lg: 'var(--spacing-lg)',
        xl: 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      ringColor: {
        brand: 'var(--color-focus-ring)',
      },
      fontFamily: {
        sans: "var(--font-sans, 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif)",
      },
      minWidth: {
        module: '280px',
      },
    },
  },
  plugins: [],
}

export default config
