export { DashboardShell } from './DashboardShell'
export type { DashboardShellProps } from './DashboardShell'
export { DashboardClientsPanel } from './DashboardClientsPanel'
export type { DashboardClientsPanelProps } from './DashboardClientsPanel'
export { DashboardCenterPanel } from './DashboardCenterPanel'
export type { DashboardCenterPanelProps } from './DashboardCenterPanel'
export { DashboardTimePanel } from './DashboardTimePanel'
export type { DashboardTimePanelProps } from './DashboardTimePanel'
export { DashboardDockControls } from './DashboardDockControls'
export type { DashboardDockControlsProps } from './DashboardDockControls'
